import type { Metadata } from "next";
import { LoginForm } from "@/components/auth/login-form";

export const metadata: Metadata = {
  title: "Sign in — JAN-AI",
};

// A SERVER component that reads the URL and hands the useful part to a CLIENT
// form. That split is deliberate: `searchParams` is a server concern, and the
// form needs browser state — so each does the half it is suited to, and the
// client bundle stays as small as the form itself.
//
// ---- searchParams IS A PROMISE, AND THAT IS NEW IN NEXT 16 -----------------
//
// Synchronous access to `searchParams`, `params`, `cookies()` and `headers()`
// was deprecated in Next 15 and REMOVED in 16. They must be awaited now.
//
// The reason is streaming: Next wants to start rendering the page before it has
// necessarily finished parsing the request, so these became promises. Awaiting
// one marks the point where the render genuinely needs the value.
//
// `PageProps<"/login">` is generated by Next from the route tree (`next
// typegen`), so the route string is checked against real routes and the shape
// of params/searchParams comes with it.
export default async function LoginPage(props: PageProps<"/login">) {
  const { next } = await props.searchParams;

  // A repeated query key (`?next=/a&next=/b`) arrives as an array. Rather than
  // guess which one was meant, treat that as absent — the same rule the backend
  // uses for repeated query params.
  const nextPath = typeof next === "string" ? next : null;

  return (
    <div className="space-y-8">
      <div>
        <h1 className="display-wide text-h1 text-ink">Sign in</h1>
        <p className="mt-2 text-ink-muted">
          Report an issue, or track one you have already filed.
        </p>
      </div>

      {/* The raw value is passed through unvalidated ON PURPOSE — it is
          sanitised by safeNextPath() at the moment of navigation, inside the
          form. Validating here as well would mean two places that have to agree
          about what a safe path is. One gate, at the point of use. */}
      <LoginForm next={nextPath} />
    </div>
  );
}
